// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

// import type { ReactNode } from "react";

// export default function layout({
//   children,
// }: {
//   children: ReactNode;
// }) {
//   return (
//     <main className="min-h-screen bg-slate-50">
//       <div className="mx-auto flex min-h-screen max-w-7xl">
//         {/* Branding */}
//         <section className="hidden w-1/2 flex-col justify-center bg-slate-900 px-16 text-white lg:flex">
//           <div className="max-w-md">
//             <p className="mb-4 text-sm font-semibold uppercase tracking-[0.2em] text-slate-300">
//               Village Portal
//             </p>

//             <h1 className="text-5xl font-bold tracking-tight">
//               Your village.
//               <br />
//               Your community.
//             </h1>

//             <p className="mt-6 text-lg leading-8 text-slate-300">
//               Stay connected with village news, events, videos,
//               gallery updates and important information.
//             </p>
//           </div>
//         </section>

//         {/* Authentication */}
//         <section className="flex w-full items-center justify-center px-6 py-12 lg:w-1/2">
//           {children}
//         </section>
//       </div>
//     </main>
//   );
// }

import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: "Village Portal",
    template: "%s | Village Portal",
  },
  description:
    "Village Portal - News, events, videos, gallery and community information.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}